# Generated by Django 5.1.5 on 2025-02-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseinfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["course_number", "course_name"]},
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("course_number", "course_name"), name="unique_course"
            ),
        ),
    ]
